security:
    encoders:
        App\entity\User:
            algorithm:   argon2i
            memory_cost: 4092
            time_cost:   10
    providers:
        users:
            entity:
                class: App\Entity\User
                property: uuid
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/users/connect$
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            json_login:
                check_path:      /users/connect
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            stateless: true
            anonymous: false
            provider: users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/users/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/connect,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: IS_AUTHENTICATED_FULLY }
